version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wdio/mocha-framework"
    versions:
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.1.2
    - 7.2.0
    - 7.2.1
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.6
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: chromedriver
    versions:
    - 88.0.0
    - 89.0.0
