language: node_js
node_js:
  - "node"
git:
  quiet: true
branches:
  only:
    - master
services:
  - docker
addons:
  artifacts:
    paths:
      - ./reports
before_install:
  - docker-compose pull
  - docker-compose up -d
install:
  - npm install
script:
  - npm run test
cache: npm
