language: node_js
node_js:
  - "node"
git:
  quiet: true
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - npm install
script:
  - npm run test
cache: npm
